language: node_js
node_js:
  - "7"
env:
  global:
  - 'SFTP_USER=enotifyfiles'
  - 'SFTP_PASSWORD=Twsslsbnstas1'
after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@enotify.iodrop.net