language: node_js
node_js:
  - "7"

# before_script:
#   - echo "export TRAVIS_HOME=$TRAVIS_HOME" | cat - ~/.bashrc > ~/.bashrc.mod
#   - mv -v ~/.bashrc.mod ~/.bashrc

before_install:
- openssl aes-256-cbc -K $encrypted_e68d65decd06_key -iv $encrypted_e68d65decd06_iv -in ./config/config.json.enc -out ./config/config.json -d

#env:
#  global:
#  - 'SFTP_USER=[username]'
#  - 'SFTP_PASSWORD=[password]'
#  - 'SFTP_KEY=[key]'

#  after_success:
#- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#- curl --ftp-create-dirs
#       -T filename
#       --key /tmp/sftp_rsa
#       sftp://${SFTP_USER}:${SFTP_PASSWORD}@enotify.iodrop.net

#script:
#- echo "skipping tests"